/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication1.LoginScreen.utilizatorPublic;
import static javaapplication1.MainApp.insertProfileInfo;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author adeli
 */
public class InformatiiProfil extends javax.swing.JFrame {

    /**
     * Creates new form InformatiiProfil
     */static String prenumePublic;
    public InformatiiProfil() {
        initComponents();
       this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        InfoGetterPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblPrenumeGetInfo = new javax.swing.JTextField();
        lblGreutateGetInfo = new javax.swing.JTextField();
        lblInaltimeGetInfo = new javax.swing.JTextField();
        radioFoarteGetInfo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        radioSedentarGetInfo = new javax.swing.JRadioButton();
        radioMaiPutinGetInfo = new javax.swing.JRadioButton();
        radioActivGetInfo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        comboSexGetInfo = new javax.swing.JComboBox<>();
        InsertProfileData = new javax.swing.JButton();
        lblVarstaGetInfo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InfoGetterPanel.setBackground(new java.awt.Color(59, 70, 82));
        InfoGetterPanel.setPreferredSize(new java.awt.Dimension(800, 678));
        InfoGetterPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(43, 61, 76));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/img/InfoProfil.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel6)
                .addContainerGap(226, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        InfoGetterPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        InfoGetterPanel.add(lblPrenumeGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 280, 40));
        InfoGetterPanel.add(lblGreutateGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 280, 40));
        InfoGetterPanel.add(lblInaltimeGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 280, 40));

        radioFoarteGetInfo.setText("Foarte activ");
        InfoGetterPanel.add(radioFoarteGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sex");
        InfoGetterPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 280, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prenume (optional)");
        InfoGetterPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 280, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Greutate");
        InfoGetterPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 280, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inaltime (cm)");
        InfoGetterPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 280, 30));

        radioSedentarGetInfo.setText("Sedentar");
        InfoGetterPanel.add(radioSedentarGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, -1, -1));

        radioMaiPutinGetInfo.setText("Mai putin activ");
        InfoGetterPanel.add(radioMaiPutinGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        radioActivGetInfo.setText("Activ");
        InfoGetterPanel.add(radioActivGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nivel de activitate");
        InfoGetterPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 280, 30));

        comboSexGetInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));
        InfoGetterPanel.add(comboSexGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 200, 30));

        InsertProfileData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/img/butonUpdateProfil.png"))); // NOI18N
        InsertProfileData.setBorder(null);
        InsertProfileData.setBorderPainted(false);
        InsertProfileData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertProfileDataActionPerformed(evt);
            }
        });
        InfoGetterPanel.add(InsertProfileData, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, -1, -1));
        InfoGetterPanel.add(lblVarstaGetInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 280, 40));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Varsta");
        InfoGetterPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 280, 30));

        getContentPane().add(InfoGetterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 778, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertProfileDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertProfileDataActionPerformed
        // TODO add your handling code here:
        boolean alreadySelected=false,readyToInsert=true;
        String varsta,greutate,inaltime,activitate,sex,utilizator,prenume;
        activitate="Activ";
        varsta=lblVarstaGetInfo.getText();
        greutate=lblGreutateGetInfo.getText();
        inaltime=lblInaltimeGetInfo.getText();
        prenume=lblPrenumeGetInfo.getText();
        prenumePublic=prenume;
        utilizator=utilizatorPublic;
        if(radioSedentarGetInfo.isSelected())
        {
            
            if(!alreadySelected)
            {
                activitate="Sedentar";
            }
            alreadySelected=true;
        }
         if(radioMaiPutinGetInfo.isSelected())
        {
           
            if(!alreadySelected)
            {
                activitate="Mai putin activ";
            }
            alreadySelected=true;
        }
        if(radioActivGetInfo.isSelected())
        {
           
            if(!alreadySelected)
            {
                activitate="Activ";
            }
            alreadySelected=true;
        }
        if(radioFoarteGetInfo.isSelected())
        {
           
            if(!alreadySelected)
            {
                activitate="Foarte activ";
            }
            alreadySelected=true;
        }
        sex=comboSexGetInfo.getSelectedItem().toString();
        if(varsta.equals("")||greutate.equals("")||inaltime.equals(""))readyToInsert=false;
        try {
            if(readyToInsert)insertProfileInfo(varsta,greutate,inaltime,activitate,sex,utilizator,prenume);
            else 
            {
           JOptionPane.showMessageDialog(null,"Nu ati introdus toate datele necesare !");
            }
        } catch (SQLException ex) {
            Logger.getLogger(InformatiiProfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        MainScreen gotoMain = null;
         try {
             gotoMain = new MainScreen();
         } catch (SQLException ex) {
             Logger.getLogger(InformatiiProfil.class.getName()).log(Level.SEVERE, null, ex);
         }
         if(readyToInsert){this.setVisible(false);
        gotoMain.setVisible(true);}
        
    }//GEN-LAST:event_InsertProfileDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformatiiProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformatiiProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformatiiProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformatiiProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformatiiProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoGetterPanel;
    private javax.swing.JButton InsertProfileData;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboSexGetInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lblGreutateGetInfo;
    private javax.swing.JTextField lblInaltimeGetInfo;
    private javax.swing.JTextField lblPrenumeGetInfo;
    private javax.swing.JTextField lblVarstaGetInfo;
    private javax.swing.JRadioButton radioActivGetInfo;
    private javax.swing.JRadioButton radioFoarteGetInfo;
    private javax.swing.JRadioButton radioMaiPutinGetInfo;
    private javax.swing.JRadioButton radioSedentarGetInfo;
    // End of variables declaration//GEN-END:variables
}
