/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javaapplication1.MainApp.getQuestion;
import static javaapplication1.MainApp.readAnswer;
import static javaapplication1.MainApp.updatePassword;
import javax.swing.JOptionPane;

/**
 *
 * @author adeli
 */
public class PassRecovery extends javax.swing.JFrame {

    /**
     * Creates new form PassRecovery
     */
    public PassRecovery() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIntrebare = new javax.swing.JTextField();
        textRaspuns = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textNumeDat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        buttonRecover = new javax.swing.JButton();
        GetQuestion = new javax.swing.JButton();
        newPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textIntrebare.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setText("Intrebare");

        jLabel2.setText("Raspuns");

        textNumeDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNumeDatActionPerformed(evt);
            }
        });

        jLabel3.setText("Nume utilizator");

        buttonRecover.setText("SCHIMBA PAROLA");
        buttonRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRecoverActionPerformed(evt);
            }
        });

        GetQuestion.setText("Primeste intrebarea");
        GetQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetQuestionActionPerformed(evt);
            }
        });

        newPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPassActionPerformed(evt);
            }
        });

        jLabel4.setText("Introduceti noua parola");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(buttonRecover)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newPass, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textIntrebare)
                            .addComponent(textRaspuns)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNumeDat, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(GetQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNumeDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GetQuestion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textIntrebare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textRaspuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonRecover)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNumeDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNumeDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNumeDatActionPerformed

    private void buttonRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRecoverActionPerformed
        // TODO add your handling code here:
        boolean allOk=true;
        String user,answer,newPassword;
        user=textNumeDat.getText();
        answer=textRaspuns.getText();
        newPassword=newPass.getText();
        
        if(answer.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Nu ati raspuns la intrebare !");
             allOk=false;
        }
        else allOk=true;
        
        if(user.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Introduceti numele de utilizator !");
             allOk=false;
        }
        else allOk=true;
        
        if(newPassword.equals(""))
        {
             JOptionPane.showMessageDialog(null,"Introduceti o parola noua !");
             allOk=false;
        }
        else allOk=true;
        int verif=0;
        
        try {
            verif=readAnswer(user,answer); // verificare raspuns de securitate
        } catch (SQLException ex) {
            Logger.getLogger(PassRecovery.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.println(verif);
       if(allOk) if(verif==1) // Toate campurile completate + raspunsurile se potrivesc
        {
            try {
                updatePassword(user,newPassword);// Schimbare parola
                this.setVisible(false);
                LoginScreen login = new LoginScreen(); // revenire la ecranul de LOGIN
                login.setVisible(true);
                JOptionPane.showMessageDialog(null,"Parola a fost schimbata cu succes !");
            } catch (SQLException ex) {
                Logger.getLogger(PassRecovery.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Date incorecte !");
        }
    }//GEN-LAST:event_buttonRecoverActionPerformed

    private void GetQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetQuestionActionPerformed
        // TODO add your handling code here:
        String user=textNumeDat.getText(); 
        String intrebare=null;
        try {
            intrebare=getQuestion(user); // Cauta intrebarea de securitate specifica utilizatorului curent
        } catch (SQLException ex) {
            Logger.getLogger(PassRecovery.class.getName()).log(Level.SEVERE, null, ex);
        }
        textIntrebare.setText(intrebare);
        if(intrebare==null)
        {
            JOptionPane.showMessageDialog(null,"Utilizatorul nu a fost gasit !");     
        }
        
    }//GEN-LAST:event_GetQuestionActionPerformed

    private void newPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassRecovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GetQuestion;
    private javax.swing.JButton buttonRecover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JTextField textIntrebare;
    private javax.swing.JTextField textNumeDat;
    private javax.swing.JTextField textRaspuns;
    // End of variables declaration//GEN-END:variables
}
